[PHP]

; Direktori ekstensi
extension_dir = "C:\Program Files\Apache\ext"

; Mengaktifkan modul-modul penting (Urutan sangat penting)
extension=curl
extension=fileinfo
extension=mbstring
extension=openssl
extension=pdo_mysql
extension=mysqli
extension=sqlite3
extension=pdo_sqlite
extension=gd

; Pengaturan dasar
memory_limit = 512M
upload_max_filesize = 100M
post_max_size = 100M
display_errors = On
error_reporting = E_ALL

; Pengaturan Database
mysql.default_port = 3307
mysqli.default_port = 3307
